Repository AmericanAirlines/Flight-Engine, pull requests merged in 2019-09, with the labels that each got.

#2 Implementing /flights feature
  .eslintrc.js
  .gitignore
  package-lock.json
  package.json
  src/Data/aircraft.test.ts
  src/Data/aircraft.ts
  src/Data/airports.test.ts
  src/Data/airports.ts
  src/Generator.test.ts
  src/Generator.ts
  src/Types/index.d.ts
  src/app.ts
Labels: enhancement

#9 Creating initial Actions
  .github/workflows/nodejs.yml
Labels: enhancement

#15 Add Deploy to Heroku button
  README.md
  app.json
Labels: enhancement

#11 Flights cache
  README.md
  src/FlightCache.test.ts
  src/FlightCache.ts
  src/Generator.test.ts
  src/Generator.ts
  src/app.test.ts
  src/app.ts
Labels: bug, enhancement

#17 Add cors express middleware
  package-lock.json
  package.json
  src/app.ts
Labels: bug
